### ISSUE TITLE
又有死了妈的为了流量推广f k了

### ISSUE THREAD

**Issue by lhj1012** [Xposed-Modules-Repo/org.hello.coolapk#4]
公众号链接：https://mp.weixin.qq.com/s?__biz=Mzk0MzMxMTQzMg==&mid=2247484150&idx=1&sn=ffbba1e55921ef2dc5dc2efc690d6d51&chksm=c3349dd1f44314c7e8216a164bc0caccd95433da5add608180b5ffe8497dece7bf56ba100361&mpshare=1&scene=23&srcid=0324WNe2pDHGUwdOEYU1skFg&sharer_sharetime=1648088036290&sharer_shareid=b42c1c817cf35346789c0e4162fc7007#rd
公众号管理员：
姓名:倪**
手机:187********[湖北****][倪**]
邮箱:100*******@qq.com
身份证:420***************
车牌:鄂A*****
QQ绑定:100*******
微博绑定:https://www.weibo.com/u/519*******

**Comment by lz233** [comment]
这没有必要（

（相关信息已做隐私处理，想查看真实信息的可以看 original issue）
