### ISSUE TITLE
Is it necessary to hide this module

### ISSUE THREAD

**Issue by lingfantang** [Xposed-Modules-Repo/org.hello.coolapk#5]
Noticed that the Applist Detector is just not able to find this module even though I haven't come to do any extra settings.

And I checked the issue#1 about HMA and then find that the two ways "File detections" and "Maps scan" would both make the latest CookApk crash. I also tried the PrivacySpace, but unfortunately my phone crashed..
So I wonder if it is enough to hide this module with the only three valid ways of HMA.
(or are there some other ways to hide it ((is that what i can say..

**Comment by lz233** [comment]
From my known information, theoretically it is enough to hide module by activating HMA because of the broken of Map Scan.

At this stage, Coolapk doesn't have targeted means to detect FCR, but still some users reported that their accounts was banned. So I don't know what else happened.

**Comment by o7451** [comment]
sad！
